[package]
name = "orxnre"
version = "0.3.0"
edition = "2021"
authors = ["Xnye"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored = "2.0.4"
console = "0.15.7"
noise = "0.8.2"
lazy_static = "1.4.0"